#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
#
# Writes mali_shader_cache_id.h: a hash of every source file that can change
# the shader binaries our pipeline cache stores. pipelineCacheUUID is derived
# from it, so an application's pipeline cache survives a driver update that
# does not touch the compiler, and is thrown away when one does.
#
# Hashing too much only costs a needless recompile; hashing too little lets a
# stale shader binary be reused. So the hash covers the whole source tree and
# leaves out only files that cannot reach a shader: the kernel interface, the
# measurement layer, and the command-buffer, queue, memory and window-system
# code in src/vk. Headers are always included.
#
# The output file is only rewritten when the hash changes, so the target can
# run on every build without forcing a relink.

import argparse
import hashlib
import os

# Directories and top-level files hashed, relative to the source root. Of
# Mesa, only the directories the build compiles from.
ROOTS = ['src', 'mesa-glue', 'cross', 'meson.build', 'meson.options',
         'mesa/include', 'mesa/src/c11', 'mesa/src/compiler', 'mesa/src/panfrost',
         'mesa/src/util', 'mesa/src/vulkan']

# Files under src/ that do not affect shader compilation or the serialized
# shader format. Only .c files and build helpers; headers stay in.
EXCLUDE_DIRS = ['src/kbase', 'src/measurement']
EXCLUDE_FILES = {
    'src/vk/mali_android.c',
    'src/vk/mali_bo_pool.c',
    'src/vk/mali_buffer.c',
    'src/vk/mali_cmd_buffer.c',
    'src/vk/mali_cmd_copy.c',
    'src/vk/mali_cmd_dispatch.c',
    'src/vk/mali_cmd_draw.c',
    'src/vk/mali_cmd_image.c',
    'src/vk/mali_cmd_render.c',
    'src/vk/mali_descriptor_set.c',
    'src/vk/mali_device_memory.c',
    'src/vk/mali_formats.c',
    'src/vk/mali_icd.c',
    'src/vk/mali_icd.sym',
    'src/vk/mali_icd_android.sym',
    'src/vk/mali_image.c',
    'src/vk/mali_image_layout.c',
    'src/vk/mali_image_view.c',
    'src/vk/mali_instance.c',
    'src/vk/mali_queue.c',
    'src/vk/mali_sampler.c',
    'src/vk/mali_sync.c',
    'src/vk/mali_sync_file.c',
    'src/vk/mali_waist.c',
    'src/vk/mali_wsi.c',
    'src/vk/waist.txt',
    'src/vk/gen_waist_stubs.py',
    'src/vk/mali_version.h.in',
    'src/vk/gen_shader_cache_id.py',
}


def excluded(rel):
    if rel in EXCLUDE_FILES:
        return True
    if '__pycache__' in rel.split('/'):
        return True
    return any(rel.startswith(d + '/') for d in EXCLUDE_DIRS)


def tree_files(root):
    out = []
    for r in ROOTS:
        p = os.path.join(root, r)
        if os.path.isfile(p):
            out.append(r)
            continue
        for d, dirs, files in os.walk(p):
            dirs.sort()
            for f in files:
                rel = os.path.relpath(os.path.join(d, f), root).replace(os.sep, '/')
                if not excluded(rel):
                    out.append(rel)
    return sorted(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--root', required=True)
    ap.add_argument('--extra', action='append', default=[],
                    help='a string that also goes into the hash (build options)')
    ap.add_argument('--out-h', required=True)
    args = ap.parse_args()

    h = hashlib.sha256()
    for extra in args.extra:
        h.update(b'extra\0' + extra.encode() + b'\0')
    for rel in tree_files(args.root):
        h.update(rel.encode() + b'\0')
        path = os.path.join(args.root, rel)
        # A symlink inside a tree (Mesa has a few, into its docs/) counts by
        # its target path: the target may not be copied along.
        if os.path.islink(path):
            data = b'symlink\0' + os.readlink(path).encode()
        else:
            with open(path, 'rb') as f:
                data = f.read()
        h.update(len(data).to_bytes(8, 'little'))
        h.update(data)

    text = ('/* Generated by gen_shader_cache_id.py: hash of the sources that\n'
            ' * can change shader binaries. */\n'
            '#define MALI_SHADER_CACHE_ID "%s"\n'
            '#define MALI_SHADER_CACHE_ID_SHORT "%s"\n' % (h.hexdigest(), h.hexdigest()[:12]))
    try:
        with open(args.out_h) as f:
            if f.read() == text:
                return
    except OSError:
        pass
    with open(args.out_h, 'w') as f:
        f.write(text)


if __name__ == '__main__':
    main()
