#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 ARMSX2 and bmdhacks
# SPDX-License-Identifier: MIT
"""Generate the waist stub entry points from waist.txt.

For every name in waist.txt this writes one function mali_waist_<Name> with
the exact prototype from vk.xml (aliases share their core name's stub).
The function reports the call to mali_waist.c and, if it returns a value,
returns the waist error (VkResult) or 0. vk_entrypoints_gen.py, run with
--prefix mali_waist, turns these functions into the mali_waist_*_entrypoints
tables that the instance, physical device and device layer under the
driver's and Mesa's common entry points.

Usage: gen_waist_stubs.py --xml vk.xml --vk-util <dir with vk_entrypoints.py>
                          --waist waist.txt --out-c out.c
"""

import argparse
import sys


def read_waist(path):
    rows = []
    for lineno, line in enumerate(open(path), 1):
        line = line.split('#', 1)[0].split()
        if not line:
            continue
        flags = set(line[2:])
        if line[0] not in ('a', 'b', 'c', 'd') or len(line) < 2 or \
                not flags <= {'nonnull', 'noregistry'}:
            sys.exit(f'{path}:{lineno}: expected "<a|b|c|d> vkName [nonnull] [noregistry]"')
        rows.append((line[0], line[1], flags))
    return rows


def main():
    p = argparse.ArgumentParser()
    p.add_argument('--xml', required=True)
    p.add_argument('--vk-util', required=True)
    p.add_argument('--waist', required=True)
    p.add_argument('--out-c', required=True)
    args = p.parse_args()

    sys.path.insert(0, args.vk_util)
    from vk_entrypoints import get_entrypoints_from_xml

    by_name = {'vk' + e.name: e for e in get_entrypoints_from_xml([args.xml], False)}

    # One stub per core entry point; the first row that names it (in class
    # order a, b, c, d) gives it its class.
    stubs = {}
    for cls, name, flags in read_waist(args.waist):
        e = by_name.get(name)
        if 'noregistry' in flags:
            if e is not None:
                sys.exit(f'{args.waist}: {name} is marked noregistry but is in vk.xml')
            continue
        if e is None:
            sys.exit(f'{args.waist}: {name} is not a Vulkan command in vk.xml')
        nonnull = 'nonnull' in flags
        core = e.alias if e.alias else e
        s = stubs.setdefault(core.name, {'e': core, 'cls': cls, 'names': [],
                                         'nonnull': False})
        s['names'].append(name)
        s['nonnull'] |= nonnull

    out = []
    w = out.append
    w('/* Generated by gen_waist_stubs.py from waist.txt. Do not edit. */\n\n')
    w('#include "mali_entrypoints.h"\n')
    w('#include "mali_waist.h"\n\n')

    w('struct mali_waist_entry mali_waist_entries[] = {\n')
    ordered = sorted(stubs.values(), key=lambda s: s['e'].name)
    for s in ordered:
        e = s['e']
        names = ' '.join(s['names'])
        w(f'   {{ "vk{e.name}", "{names}", \'{s["cls"]}\', '
          f'{"true" if s["nonnull"] else "false"}, 0 }},\n')
    w('};\n\n')
    w(f'const unsigned mali_waist_entry_count = {len(ordered)};\n\n')

    for i, s in enumerate(ordered):
        e = s['e']
        if e.guard:
            w(f'#ifdef {e.guard}\n')
        w(f'VKAPI_ATTR {e.return_type} VKAPI_CALL\n')
        w(f'mali_waist_{e.name}({e.decl_params()})\n{{\n')
        if e.return_type == 'void':
            w(f'   mali_waist_void_call(&mali_waist_entries[{i}]);\n')
        elif e.return_type == 'VkResult':
            w(f'   return mali_waist_result_call(&mali_waist_entries[{i}]);\n')
        else:
            w(f'   mali_waist_value_call(&mali_waist_entries[{i}]);\n')
            w(f'   return ({e.return_type})0;\n')
        w('}\n')
        if e.guard:
            w(f'#endif /* {e.guard} */\n')
        w('\n')

    open(args.out_c, 'w').write(''.join(out))


if __name__ == '__main__':
    main()
