#!/usr/bin/env python3
# Copyright 2026 The libmali authors
# SPDX-License-Identifier: MIT
"""List the NIR instructions kraid's NIR translator handles.

kraid (vendored, Rust) translates NIR in kraid/nir.rs. Its parse_alu,
parse_tex and parse_intrinsic functions match on the opcode and end in a
panic!() for anything they do not know; a Rust panic across the C boundary
aborts the process. This script collects the opcode names those three
functions name, so mali_compiler.c can refuse a shader that still contains
anything else when it reaches kraid, instead of letting the process die.

The lists are over-inclusive on purpose (any name mentioned in the function
body counts as handled): the check must never refuse a shader kraid would
compile. Names are checked against NIR's own opcode tables.

Usage: gen_kraid_support.py --nir-rs kraid/nir.rs --nir-dir compiler/nir
                            --out-h out.h
"""

import argparse
import re
import sys


def function_bodies(src, names):
    """Return {name: body text} for the `fn name(` definitions in src."""
    bodies = {}
    for name in names:
        m = re.search(r'\bfn ' + name + r'\s*\(', src)
        if not m:
            sys.exit(f'kraid nir.rs: no fn {name}; update gen_kraid_support.py')
        # The body is the first brace block after the signature.
        i = src.index('{', m.end())
        depth = 0
        for j in range(i, len(src)):
            if src[j] == '{':
                depth += 1
            elif src[j] == '}':
                depth -= 1
                if depth == 0:
                    bodies[name] = src[i:j + 1]
                    break
    return bodies


def strip_comments(src):
    src = re.sub(r'//[^\n]*', '', src)
    return re.sub(r'/\*.*?\*/', '', src, flags=re.S)


def main():
    p = argparse.ArgumentParser()
    p.add_argument('--nir-rs', required=True)
    p.add_argument('--nir-dir', required=True)
    p.add_argument('--out-h', required=True)
    args = p.parse_args()

    sys.path.insert(0, args.nir_dir)
    from nir_opcodes import opcodes
    from nir_intrinsics import INTR_OPCODES

    src = strip_comments(open(args.nir_rs).read())
    bodies = function_bodies(src, ['parse_alu', 'parse_tex', 'parse_intrinsic',
                                   'parse_block'])

    alu = sorted(set(re.findall(r'\bnir_op_(\w+)', bodies['parse_alu'])) &
                 set(opcodes))
    intr = sorted(set(re.findall(r'\bnir_intrinsic_(\w+)',
                                 bodies['parse_intrinsic'])) & set(INTR_OPCODES))
    texop = sorted(set(re.findall(r'\bnir_texop_(\w+)', bodies['parse_tex'])))
    texsrc = sorted(set(re.findall(r'\bnir_tex_src_(\w+)', bodies['parse_tex'])))
    itype = sorted(set(re.findall(r'\bnir_instr_type_(\w+)', bodies['parse_block'])))

    if len(alu) < 50 or len(intr) < 20 or not texop or not itype:
        sys.exit('kraid nir.rs: implausibly few opcodes found; the parser '
                 'layout changed, update gen_kraid_support.py')

    out = ['/* Generated by gen_kraid_support.py from kraid/nir.rs. Do not edit. */\n']
    for cname, prefix, names in [
        ('mali_kraid_alu_ops', 'nir_op_', alu),
        ('mali_kraid_intrinsics', 'nir_intrinsic_', intr),
        ('mali_kraid_texops', 'nir_texop_', texop),
        ('mali_kraid_tex_srcs', 'nir_tex_src_', texsrc),
        ('mali_kraid_instr_types', 'nir_instr_type_', itype),
    ]:
        out.append(f'static const unsigned {cname}[] = {{\n')
        out += [f'   {prefix}{n},\n' for n in names]
        out.append('};\n\n')
    open(args.out_h, 'w').write(''.join(out))


if __name__ == '__main__':
    main()
